### ISSUE TITLE
 proto: syntax error (line 1:1): unexpected token 

### ISSUE THREAD

**Issue by lohrm-stabl** [reviewdog/action-trivy#17]
With the following action:
```
name: Trivy Checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Choose the Node.js version as per your project requirements

    - name: Install project dependencies
      run: yarn install 
  
    - name: Install CDKTF CLI and TypeScript
      run: yarn global add cdktf-cli@0.19.2 typescript
            
    - name: Sythesizing
      run: |
		cd src
        cdktf get
        cdktf synth --output .

    - name: Run trivy with reviewdog output on the PR
      uses: reviewdog/action-trivy@v1
      with:
        github_token: ${{ secrets.github_token }}
        working_directory: src/
        level: info # Get more output from reviewdog
        reporter: github-pr-review # Change reviewdog reporter
        filter_mode: nofilter # Check all files, not just the diff
        fail_on_error: true # Fail action if errors are found
        flags: -tee # Add debug flag to reviewdog
```

Gives the following output:
```
Run reviewdog/action-trivy@v1
Run $GITHUB_ACTION_PATH/script.sh
  $GITHUB_ACTION_PATH/script.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    REVIEWDOG_VERSION: v0.16.0
    INPUT_GITHUB_TOKEN: ***
    INPUT_WORKING_DIRECTORY: src/
    INPUT_LEVEL: info
    INPUT_REPORTER: github-pr-review
    INPUT_TOOL_NAME: trivy
    INPUT_FILTER_MODE: nofilter
    INPUT_FAIL_ON_ERROR: true
    INPUT_FLAGS: -tee
    INPUT_TRIVY_VERSION: latest
    INPUT_TRIVY_COMMAND: 
    INPUT_TRIVY_TARGET: 
    INPUT_TRIVY_FLAGS: 
Preparing ...
  Detected Linux running on 64bit, will install tools in /tmp/tmp.IOSNi5XqPh
🐶 Installing reviewdog (v0.16.0) ... https://github.com/reviewdog/reviewdog
  reviewdog/reviewdog info checking GitHub for tag 'v0.16.0'
  reviewdog/reviewdog info found version: 0.16.0 for v0.16.0/Linux/x86_64
  reviewdog/reviewdog info installed /tmp/tmp.IOSNi5XqPh/reviewdog/reviewdog
 Installing trivy (latest) ... https://github.com/aquasecurity/trivy
  Downloading https://github.com/aquasecurity/trivy/releases/download/v0.48.3/trivy_0.48.3_Linux-64bit.tar.gz
 Print trivy details ...
  Version: 0.48.3
 Running trivy with reviewdog 🐶 ...
  reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): unexpected token 
Error: Process completed with exit code 1.
```
