### ISSUE TITLE
Error on launching the default example

### ISSUE THREAD

**Issue by irizzant** [reviewdog/action-trivy#45]
I tried to execute the action with this workflow
```

# Run continuous integration

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
    inputs:
      severity:
        description: 'Severity level to scan for'
        required: false
        default: 'CRITICAL,HIGH'
        type: string

permissions:
  contents: write
  checks: write
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: false
          cache: 'maven'
      - name: Build with Maven
        run: 'mvn package'
        shell: bash
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/java-template:${{ github.sha }} .
      - name: Trivy Cache
        uses: yogeshlonkar/trivy-cache-action@v0.1.5
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run trivy with reviewdog output on the PR
        uses: reviewdog/action-trivy@v1.5.2
        with:
          github_token: ${{ secrets.github_token }}
          trivy_command: config # Change trivy command
          trivy_target: . # Change trivy target directory
          level: info # Get more output from reviewdog
          reporter: github-pr-review # Change reviewdog reporter
          filter_mode: nofilter # Check all files, not just the diff
          fail_on_error: false # Fail action if errors are found
          flags: -tee # Add debug flag to reviewdog
          trivy_flags: "" # Optional
      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          cache-dir: '.trivy'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
      - name: Run static analysis
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          cache-dir: '.trivy'
          format: 'table'
          severity: ${{ github.event.inputs.severity }}

```

The action reports an error
![immagine](https://github.com/reviewdog/action-trivy/assets/15982257/c719620a-4bb7-42ad-8dc3-d715c29cccfe)

but I see no review created on my PR
